on: 
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./codebase/rdicidr-0.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '15'

      - name: Install Dependencies
        run: npm install --engine-strict=false --legacy-per-deps

      - name: Install Linter
        run: npm run lint

      - name: Test
        run: npm run test
        env:
          CI: true

      - name: Build
        run: npm run build

  push-to-ecr:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: assessment-fsl
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./codebase/rdicidr-0.1.0
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest     
        
